services:
 api:
   build:
     context: .
   env_file:
     - .env
   ports:
     - "8000:8000"
   command: >
      sh -c "python api_rick_and_morty/wait_db.py &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000
            "
   volumes:
     - /Users/kostyantynzivenko/Desktop/MateAcademy/api_rick_and_morty:/app
   depends_on:
     - db
     - redis

 redis:
   image: redis
   restart: always
   ports:
     - "6379:6379"

 db:
   image: postgres:16.0-alpine3.17
   restart: always
   env_file:
     - .env
   ports:
     - "5432:5432"
   volumes:
     - my_db:$PGDATA

 celery_worker:
    build:
      context: .
    command: celery -A api_rick_and_morty worker -l INFO
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - api

 celery_beat:
    build:
      context: .
    command: celery -A api_rick_and_morty beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    depends_on:
      - celery_worker

volumes:
  my_db: